/**
 * App Redux Action Types
 */
export const COLLAPSED_SIDEBAR = 'COLLAPSED_SIDEBAR';
export const DARK_MODE = 'DARK_MODE';
export const BOXED_LAYOUT = 'BOXED_LAYOUT';
export const RTL_LAYOUT = 'RTL_LAYOUT';
export const MINI_SIDEBAR = 'MINI_SIDEBAR';
export const SEARCH_FORM_ENABLE = 'SEARCH_FORM_ENABLE';
export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
export const TOGGLE_SIDEBAR_IMAGE = 'TOGGLE_SIDEBAR_IMAGE';
export const SET_SIDEBAR_IMAGE = 'SET_SIDEBAR_IMAGE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const START_USER_TOUR = 'START_USER_TOUR';
export const STOP_USER_TOUR = 'STOP_USER_TOUR';
export const TOGGLE_DARK_SIDENAV = 'TOGGLE_DARK_SIDENAV';

// Agency Sidebar
export const CHANGE_AGENCY_LAYOUT_BG = 'CHANGE_AGENCY_LAYOUT_BG';

// sidebar
export const TOGGLE_MENU = 'TOGGLE_MENU';

// Auth Actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const USER_COMPLETED_COUNT = 'USER_COMPLETED_COUNT';

//Test View Actions
export const TEST_VIEW_SET_IMAGE_LIST = 'TEST_VIEW_SET_IMAGE_LIST';
export const TEST_VIEW_CHANGE_IMAGE_LIST = 'TEST_VIEW_CHANGE_IMAGE_LIST';
export const TEST_VIEW_SET_SHOW_IMAGE_LIST = 'TEST_VIEW_SET_SHOW_IMAGE_LIST';
export const TEST_VIEW_SET_INITIAL_ZOOM_LEVEL = 'TEST_VIEW_SET_INITIAL_ZOOM_LEVEL';
export const TEST_VIEW_SET_SHOW_IMAGE_BROWSER = 'TEST_VIEW_SET_SHOW_IMAGE_BROWSER';
export const TEST_VIEW_SET_HANGING_TYPE = 'TEST_VIEW_SET_HANGING_TYPE';
export const TEST_VIEW_SET_RESET_ID = 'TEST_VIEW_SET_RESET_ID';
export const TEST_VIEW_SET_CASE_DENSITY = 'TEST_VIEW_SET_CASE_DENSITY';
export const TEST_VIEW_SET_CURRENT_TOOL = 'TEST_VIEW_SET_CURRENT_TOOL';
export const TEST_VIEW_SET_THICKNESS_TYPE = 'TEST_VIEW_SET_THICKNESS_TYPE';
export const TEST_VIEW_FOCUS_IMAGEVIEWER = 'TEST_VIEW_FOCUS_IMAGEVIEWER';
export const TEST_VIEW_MODALITY_INFO = 'TEST_VIEW_MODALITY_INFO';
export const TEST_VIEW_ATTEMPT_INFO = 'TEST_VIEW_ATTEMPT_INFO';

//Test View Component Actions
export const TEST_VIEW_COMP_SET_BREAST_QUALITY = 'TEST_VIEW_COMP_SET_BREAST_QUALITY';